# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: analytics 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "analytics".freeze
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Chris Van Pelt".freeze]
  s.date = "2021-04-14"
  s.description = "This gem is a simple set of helpers that make it easy to include and track events using a stock or custom build of analytics.js".freeze
  s.email = "vanpelt@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "analytics.gemspec",
    "lib/analytics.rb",
    "lib/analytics/helpers.rb",
    "lib/analytics/patches.rb",
    "lib/analytics/renderer.rb",
    "lib/templates/header.js.erb",
    "spec/analytics_spec.rb",
    "spec/spec_helper.rb",
    "vendor/analytics.js",
    "vendor/analytics.min.js.gz"
  ]
  s.homepage = "http://github.com/vanpelt/analytics".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.3".freeze
  s.summary = "Helpers for segment.io's analytics.js".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<erubis>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<faraday>.freeze, ["< 1.0"])
      s.add_runtime_dependency(%q<analytics-ruby>.freeze, ["= 1.1.0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<erubis>.freeze, [">= 0"])
      s.add_dependency(%q<faraday>.freeze, ["< 1.0"])
      s.add_dependency(%q<analytics-ruby>.freeze, ["= 1.1.0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<erubis>.freeze, [">= 0"])
    s.add_dependency(%q<faraday>.freeze, ["< 1.0"])
    s.add_dependency(%q<analytics-ruby>.freeze, ["= 1.1.0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

