# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{analytics}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Van Pelt"]
  s.date = %q{2014-06-11}
  s.description = %q{This gem is a simple set of helpers that make it easy to include and track events using a stock or custom build of analytics.js}
  s.email = %q{vanpelt@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "analytics.gemspec",
    "lib/analytics.rb",
    "lib/analytics/helpers.rb",
    "lib/analytics/patches.rb",
    "lib/analytics/renderer.rb",
    "lib/templates/header.js.erb",
    "spec/analytics_spec.rb",
    "spec/spec_helper.rb",
    "vendor/analytics.js",
    "vendor/analytics.min.js.gz"
  ]
  s.homepage = %q{http://github.com/vanpelt/analytics}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Helpers for segment.io's analytics.js}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<erubis>, [">= 0"])
      s.add_runtime_dependency(%q<faraday>, ["< 0.9.0"])
      s.add_runtime_dependency(%q<analytics-ruby>, ["~> 0.6.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["< 2.0.0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<erubis>, [">= 0"])
      s.add_dependency(%q<faraday>, ["< 0.9.0"])
      s.add_dependency(%q<analytics-ruby>, ["~> 0.6.0"])
      s.add_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["< 2.0.0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<erubis>, [">= 0"])
    s.add_dependency(%q<faraday>, ["< 0.9.0"])
    s.add_dependency(%q<analytics-ruby>, ["~> 0.6.0"])
    s.add_dependency(%q<rspec>, ["~> 2.14.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["< 2.0.0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

